### ISSUE TITLE
Create alert component

### ISSUE THREAD

**Issue by cyruzin** [cyruzin/react-redux-typescript#1]

**Comment by dubeux-waproject** [comment]
Closed on https://github.com/cyruzin/react-redux-typescript/commit/fe0da39019f3eb354769b5898cbbbb5b0232521d.

**Comment by cyruzin** [comment]
Closed on https://github.com/cyruzin/react-redux-typescript/commit/fe0da39019f3eb354769b5898cbbbb5b0232521d.
